### ISSUE TITLE
Create records for sleep tracking and save to the database

### ISSUE THREAD

**Issue by rmcc13** [rmcc13/SleepTrack#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
</code></pre>

## Current behavior

**N/A**

## Expected behavior

Users must be able to create and save records for tracking sleep. Implement the feature
end to end from the user creating the record in the UI all the way to saving it in the database

- [ ] Be able to specify whether they are going to sleep or waking up
- [ ] Be able to specify the date and time (with sane defaults)
- [ ] Store the user's specified time using their local timezone
- [ ] Use a server generated timestamp to track when the record was actually created

## Minimal reproduction of the problem with instructions

**N/A**

## What is the motivation / use case for changing the behavior?

Users must be able to track their sleep behaviors so they can track their progress
towards meeting goals.

## Environment
**N/A**
